### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by AminGtt** [TKazer/CS2_External#1]
Hello!
I got "The Os-ImGui are available only with C++17 or later." error, I can't even build the project, any idea please? 
Thanks!

**Comment by AminGtt** [comment]
PS : I got this error before and after your last commit

**Comment by TKazer** [comment]
Please build project under c++17.

**Comment by AminGtt** [comment]
I got this thanks but IDK how, I am not at all a C++ guy xD 
Im searching on the web in the same time but C++ is a pain
your help would be welcome, thanks!

**Comment by AminGtt** [comment]
Solved, I was opening the folder as a project & not a solution so I had no C++ options etc...
