### ISSUE TITLE
Offset question

### ISSUE THREAD

**Issue by xKrillexx** [TKazer/CS2_External#106]
So I pulled the repo and made some minor edits for my own personal use. Took a couple of things out that I wasn't going to use like the aim bot.

I did have a question as I am still new at this stuff and learning so apologies for the dumb question.

How do I find the updated offsets? 

Sometimes the updates happen right when I get home so it makes it not usable until several hours later when TKazer or someone else updates. I would like to be able to learn to do it myself and share it with the community to help contribute.

Can anyone point me in the right direction of where to start?

**Comment by mildnsj** [comment]
https://github.com/a2x/cs2-dumper

**Comment by xKrillexx** [comment]
Thanks!
