### ISSUE TITLE
Aimbot glitch

### ISSUE THREAD

**Issue by mikusgszyp** [TKazer/CS2_External#112]
Aimbot works on all gamemodes, but when I'm playing competitive it starts aiming next to the players, not at them

**Comment by F1ghter42** [comment]
Same, u know the fix?

**Comment by kristofhracza** [comment]
Had the same issue, change `m_angEyeAngles ` to  `v_angle `

**Comment by mikusgszyp** [comment]
okay, I needed to change GetViewAngle() code to:
`bool PlayerPawn::GetViewAngle()
{
	return GetDataAddressWithOffset<Vec2>(Address, Offset::Pawn.v_angle, this->ViewAngle);
}`

and add

`DWORD v_angle = 0x114c;`

to offsets
