### ISSUE TITLE
Only TriggerBot

### ISSUE THREAD

**Issue by Nick-Vinesmoke** [TKazer/CS2_External#114]
Hello, I wanted to select from your cheat only the trigger bot and only the dependencies necessary for it. I tried to do this, but everything was mixed in one object and there were vars and funcs for all cheat funcs, so I got confused and didn’t succeed. Because of this, I want to ask you for a favor. You can select from your cheat only a triggerbot and a team check with only the necessary parameters in the objects (which will relate to the triggerbot, and not to the aim, wh, ... which will not be) and only the necessary dependencies. I only need a trigger for personal use and don’t want to use all the other functionality. I would be very grateful. As a thank you, I can tell you about your project on my discord server, which has over 100 participants

my discord: nick_vinesmoke

**Comment by ClaudiuHBann** [comment]
You can check out [this](https://github.com/ClaudiuHBann/CS2_CP), it uses dependency injection instead of global variables, and i think it's cleaner in general.

**Comment by Nick-Vinesmoke** [comment]
Is it external software?

**Comment by Nick-Vinesmoke** [comment]
is it undetected?

**Comment by Nick-Vinesmoke** [comment]
Can you select from your cheat only a triggerbot and a team check with only the necessary parameters in the objects (which will relate to the triggerbot, and not to the aim, wh, ... which will not be) and only the necessary dependencies. I only need a trigger for personal use and don’t want to use all the other functionality.

**Comment by Nick-Vinesmoke** [comment]
pls

**Comment by Nick-Vinesmoke** [comment]
ok

**Comment by ClaudiuHBann** [comment]
If your issue has been solved can you close the issue?
