### ISSUE TITLE
AimBot.hpp

### ISSUE THREAD

**Issue by ilia45-43** [TKazer/CS2_External#116]
39. Yaw = Yaw * (1-Smooth) + Local.Pawn.ViewAngle.y;
40. Pitch = Pitch * (1 - Smooth) + Local.Pawn.ViewAngle.x;

U have to use it.

39. Yaw = Yaw * 1-Smooth + Local.Pawn.ViewAngle.y;
40. Pitch = Pitch * 1 - Smooth+ Local.Pawn.ViewAngle.x;

its ur commit)))

**Comment by ilia45-43** [comment]
aim malfunctions if used without brackets

**Comment by TKazer** [comment]
Fixed. thanks for sharing.
