### ISSUE TITLE
Detected option

### ISSUE THREAD

**Issue by DJMarkus1337** [TKazer/CS2_External#117]
TriggerBot or Bunnyhop detected

**Comment by DJMarkus1337** [comment]
![image](https://github.com/TKazer/CS2_External/assets/80347162/5d3f5854-9255-4916-a58a-627ae5122739)

**Comment by DJMarkus1337** [comment]
![image](https://github.com/TKazer/CS2_External/assets/80347162/4c9eb203-98b3-4f94-b28d-e0501fde8e19)

**Comment by DJMarkus1337** [comment]
1 TKazer On Record :D

**Comment by TKazer** [comment]
its truly detected feature, btw this project just for learning, not using.You have to solve it by self.
