### ISSUE TITLE
fix  offsets.h

### ISSUE THREAD

**Issue by pipi-ly** [TKazer/CS2_External#127]
DWORD Pos = 0x1224;
DWORD MaxHealth = 0x328;
DWORD CurrentHealth = 0x32C;
DWORD GameSceneNode = 0x310;
DWORD BoneArray = 0x1E0;
DWORD angEyeAngles = 0x1510;
DWORD vecLastClipCameraPos = 0x128C;
DWORD pClippingWeapon = 0x12A8;
DWORD iShotsFired = 0x1418;
DWORD flFlashDuration = 0x1468;
DWORD aimPunchAngle = 0x1714;
DWORD aimPunchCache = 0x1738;
DWORD iIDEntIndex = 0x153C;
DWORD iTeamNum = 0x3BF;
DWORD CameraServices = 0x10E0;
DWORD iFovStart = 0x214;
DWORD fFlags = 0x3C8;
DWORD bSpottedByMask = 0x1628 + 0xC;

**Comment by Spamm00r** [comment]
Confirmed working.

**Comment by jhondough** [comment]
Aimbot always works from behind a wall. It just doesn't work while visible.
And do you know how can i get this offsets?

**Comment by pipi-ly** [comment]
I also discovered this problem, but I don't know why

**Comment by pipi-ly** [comment]
I see, that's the offset  Not aiming at the enemy behind the wall

DWORD bSpottedByMask = 0x1630 + 0xC;

**Comment by pipi-ly** [comment]
> Aimbot always works from behind a wall. It just doesn't work while visible. And do you know how can i get this offsets?
Make some changes
DWORD bSpottedByMask = 0x1630 + 0xC;

**Comment by Hiver13** [comment]
when the opponent holds SSG then wallhack doesn't work. fix pls

**Comment by TKazer** [comment]
> when the opponent holds SSG then wallhack doesn't work. fix pls

Fixed.

**Comment by TKazer** [comment]
The offset will not be updated in the future, please update it by self.

**Comment by jhondough** [comment]
> The offset will not be updated in the future, please update it by self.

I know how to fix offsets.h but how can i reach the source to update offsets.cpp?
Like signatures etc.
