### ISSUE TITLE
process of determining the offset value 

### ISSUE THREAD

**Issue by TestMagicCode** [TKazer/CS2_External#132]
```
TempAddress = SearchOffsets(Offset::Signatures::ForceJump, ClientDLL);
if (TempAddress == 0)
	return false;

Offset::ForceJump = TempAddress + 0x30 - ClientDLL;
return true;
```

Hello! I'm curious about the process of determining the offset value, specifically the "0x30" added to the tempAddress. 
How is this value obtained? Any insights would be appreciated!

**Comment by TKazer** [comment]
These patterns come from the [cs2-dumper](https://github.com/a2x/cs2-dumper) project. Since the ForceJump data address does not have a good static bytes that can provide Bytes Scan, it is necessary to find unique static bytes in front of the address that is suitable for Bytes Scan.

**Comment by TestMagicCode** [comment]
What programs would you recommend i use to do this, i have ida, what tools do you use to get everything i would need to copy your method, i already use cs2-dumper for base offsets... do you use like cheat engine ? to get values like this "0x30"
