### ISSUE TITLE
ESP not working

### ISSUE THREAD

**Issue by danKILL11** [TKazer/CS2_External#136]
I don't know much about how the hacks works or whatever but since today's update of CS2 the **ESP stopped working**, anti-flashbang still works (I don't use aimbot so idk if it's working)
I checked this but well, I didn't understand anything: https://www.unknowncheats.me/forum/counter-strike-2-a/606196-external-esp-anymore.html

**Comment by KGAT1W** [comment]
struct
	{
		DWORD Health = 0x32C;
		DWORD TeamID = 0x3BF;
		DWORD IsAlive = 0x7DC;
		DWORD PlayerPawn = 0x5F4;
		DWORD iszPlayerName = 0x628;
	}Entity;

**Comment by toxic-grl** [comment]
> struct
> {
> 	DWORD Health = 0x32C;
> 	DWORD TeamID = 0x3BF;
> 	DWORD IsAlive = 0x7DC;
> 	DWORD PlayerPawn = 0x5F4;
> 	DWORD iszPlayerName = 0x628;
> }Entity;

I love you man! ♥
You have discord?

**Comment by KGAT1W** [comment]
> > struct
> > {
> > DWORD Health = 0x32C;
> > DWORD TeamID = 0x3BF;
> > DWORD IsAlive = 0x7DC;
> > DWORD PlayerPawn = 0x5F4;
> > DWORD iszPlayerName = 0x628;
> > }Entity;
> 
> I love you man! ♥ You have discord?

.kinggizzard

**Comment by TKazer** [comment]
No further updates will be provided here。
