### ISSUE TITLE
Aimbot not working

### ISSUE THREAD

**Issue by ZeroByteZDev** [TKazer/CS2_External#137]
New Offsets/Sig for aimbot?

**Comment by Haertas** [comment]
DWORD BulletServices = 0x16B0;

**Comment by syafiq99121** [comment]
Haertas i wanna ask u, did you get the latest offset using cs2dumper?, if yes, in which part of the file is it?

**Comment by KGAT1W** [comment]
Offset::ViewAngle = TempAddress + 21288 - ClientDLL;

**Comment by TestMagicCode** [comment]
Hey how do you get the updated values like that "21288"

**Comment by KGAT1W** [comment]
https://github.com/a2x/cs2-dumper

**Comment by jhonthedoe** [comment]
> https://github.com/a2x/cs2-dumper

Bro at where?
It is not on [client.dll.hpp](https://github.com/a2x/cs2-dumper/blob/main/generated/client.dll.hpp)

**Comment by KGAT1W** [comment]
config.json
