### ISSUE TITLE
update the cheat

### ISSUE THREAD

**Issue by syafiq99121** [TKazer/CS2_External#138]
update the offset, and please update auto offset pls

**Comment by Haertas** [comment]
can't you do it yourself?

**Comment by syafiq99121** [comment]
nope bro im new, please update auto update offset in im compile

**Comment by Haertas** [comment]
struct
{
	DWORD Health = 0x32C;
	DWORD TeamID = 0x3BF;
	DWORD IsAlive = 0x7DC;
	DWORD PlayerPawn = 0x7D4;
	DWORD iszPlayerName = 0x628;
	DWORD EnemySensor = 0x13DC;
	DWORD GravityScale = 0x434;
} Entity;

struct 
{
	DWORD BulletServices = 0x16B0;
	DWORD TotalHit = 0x40;
	DWORD Pos = 0x1224;
	DWORD MaxHealth = 0x328;
	DWORD CurrentHealth = 0x32C;
	DWORD GameSceneNode = 0x310;
	DWORD BoneArray = 0x1E0;
	DWORD angEyeAngles = 0x1510;
	DWORD vecLastClipCameraPos = 0x128C;
	DWORD pClippingWeapon = 0x12A8;
	DWORD iShotsFired = 0x1418;
	DWORD flFlashDuration = 0x1468;
	DWORD aimPunchAngle = 0x1714;
	DWORD aimPunchCache = 0x1738;
	DWORD iIDEntIndex = 0x153C;
	DWORD iTeamNum = 0x3BF;
	DWORD CameraServices = 0x10E0;
	DWORD iFovStart = 0x214;
	DWORD fFlags = 0x3C8;
	DWORD bSpottedByMask = 0x1630 + 0xC;  // entitySpottedState + bSpottedByMask
} Pawn;

struct
{
	DWORD CurrentHealth = 0x2A8; // m_iHealth
} ServerPawn;

struct
{
	DWORD dwPlantedC4 = 0x189DAF8;
	DWORD RealTime = 0x00;
	DWORD FrameCount = 0x04;
	DWORD MaxClients = 0x10;
	DWORD IntervalPerTick = 0x14;
	DWORD CurrentTime = 0x2C;
	DWORD CurrentTime2 = 0x30;
	DWORD TickCount = 0x40;
	DWORD IntervalPerTick2 = 0x44;
	DWORD CurrentNetchan = 0x0048;
	DWORD CurrentMap = 0x0180;
	DWORD CurrentMapName = 0x0188;
} GlobalVar;

struct
{
	DWORD m_hPawn = 0x5F4;
	DWORD m_pObserverServices = 0x10C0;
	DWORD m_hObserverTarget = 0x44;
	DWORD m_hController = 0x123C;
} PlayerController;

struct
{
	DWORD m_szName = 0xC18;
} WeaponBaseData;

struct
{
	DWORD m_bBeingDefused = 0xEBC;
	DWORD m_flDefuseCountDown = 0xED0;
	DWORD m_nBombSite = 0xE84;
} C4;
// Never have a try for external skin changer
struct
{
	DWORD MusicID = 0x40;
	DWORD Rank = 0x44;
	DWORD AuthoritativeWeaponSlots = 0x70;
} Inventory;

namespace Signatures
{
	const std::string InventoryServices = "E8 ?? ?? ?? ?? 8B 45 D0 48 8B 55 D8";
	const std::string GlobalVars = "48 89 0D ?? ?? ?? ?? 48 89 41";
	const std::string EntityList = "48 8B 0D ?? ?? ?? ?? 48 89 7C 24 ?? 8B FA C1";
	const std::string LocalPlayerController = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 4F";
	const std::string ViewAngles = "48 8B 0D ?? ?? ?? ?? 48 8B 01 48 FF 60 30";
	const std::string ViewMatrix = "48 8D 0D ?? ?? ?? ?? 48 C1 E0 06";
	const std::string LocalPlayerPawn = "48 8D 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 48 83 EC ?? 8B 0D";
	const std::string ForceJump = "48 8B 05 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 89 45";
}

**Comment by dongyoxuan1514** [comment]
> 结构 { DWORD 健康 = 0x32C; 双字组 ID = 0x3BF； 双字节 IsAlive = 0x7DC； DWORD PlayerPawn = 0x7D4； DWORD iszPlayerName = 0x628; 双字敌人传感器 = 0x13DC； DWORD 重力刻度 = 0x434； } 实体;
> 
> 结构 { DWORD BulletServices = 0x16B0; DWORD 总命中 = 0x40； 双字位置 = 0x1224； 双字最大健康 = 0x328； DWORD 当前健康状况 = 0x32C； DWORD 游戏场景节点 = 0x310; DWORD BoneArray = 0x1E0； 双字 angEyeAngles = 0x1510; DWORD vecLastClipCameraPos = 0x128C； 双字 pClippingWeapon = 0x12A8； 双字 iShotsFired = 0x1418； 双字 flFlashDuration = 0x1468； DWORD 目标PunchAngle = 0x1714； 双字型 TargetPunchCache = 0x1738； 双字 iIDentIndex = 0x153C； 双字 iTeamNum = 0x3BF; DWORD 相机服务 = 0x10E0; 双字 iFovStart = 0x214； 双字 fFlags = 0x3C8； DWORD bSpottedByMask = 0x1630 + 0xC；//entitySpottedState + bSpottedByMask } Pawn;
> 
> 结构 { DWORD 当前健康状况 = 0x2A8; // m_iHealth } ServerPawn;
> 
> 结构体 { DWORD dwPlantedC4 = 0x189DAF8; 双字实时 = 0x00； 双字帧计数 = 0x04； DWORD 最大客户端数 = 0x10； 双字间隔每刻度 = 0x14； DWORD 当前时间 = 0x2C； 双字当前时间2 = 0x30； 双字滴答计数 = 0x40； DWORD IntervalPerTick2 = 0x44； 双字当前Netchan = 0x0048； DWORD 当前映射 = 0x0180； DWORD 当前地图名称 = 0x0188; 全局变量；
> 
> 结构体 { DWORD m_hPawn = 0x5F4; 双字节 m_pObserverServices = 0x10C0; 双字节 m_hObserverTarget = 0x44; DWORD m_hController = 0x123C； } 玩家控制器；
> 
> 结构体 { DWORD m_szName = 0xC18; WeaponBaseData；
> 
> 结构体 { DWORD m_bBeingDefused = 0xEBC; DWORD m_flDefuseCountDown = 0xED0; 双字节 m_nBombSite = 0xE84; C4; // 永远不要尝试外部换肤器 结构 { DWORD MusicID = 0x40; 双字等级 = 0x44； DWORD 权威武器槽 = 0x70; } 存货;
> 
> 命名空间签名 { const std::string InventoryServices = "E8 ?? ?? ?? ?? 8B 45 D0 48 8B 55 D8"; const std::string GlobalVars = "48 89 0D ?? ?? ?? ?? 48 89 41"; const std::string EntityList = "48 8B 0D ?? ?? ?? ?? 48 89 7C 24 ?? 8B FA C1"; const std::string LocalPlayerController = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 4F"; const std::string ViewAngles = "48 8B 0D ?? ?? ?? ?? 48 8B 01 48 FF 60 30"; const std::string ViewMatrix = "48 8D 0D ?? ?? ?? ?? 48 C1 E0 06"; const std::string LocalPlayerPawn = "48 8D 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 48 83 EC ?? 8B 0D"; const std::string ForceJump = "48 8B 05 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 89 45"; }


Aim not working  How to solve it?

**Comment by dongyoxuan1514** [comment]
> 结构 { DWORD 健康 = 0x32C; 双字组 ID = 0x3BF； 双字节 IsAlive = 0x7DC； DWORD PlayerPawn = 0x7D4； DWORD iszPlayerName = 0x628; 双字敌人传感器 = 0x13DC； DWORD 重力重力桥梁 = 0x434； } } ;
> 
> 结构 { DWORD BulletServices = 0x16B0; DWORD 总命中 = 0x40； 双字位置 = 0x1224； 双字最大健康 = 0x328； DWORD 当前状况健康 = 0x32C； DWORD 游戏场景节点 = 0x310; DWORD BoneArray = 0x1E0； 双字 angEyeAngles = 0x1510; DWORD vecLastClipCameraPos = 0x128C； 双字 pClippingWeapon = 0x12A8； 双字 iShotsFired = 0x1418； 双字 flFlashDuration = 0x1468； DWORD targetPunchAngle = 0x1714； 双字型 TargetPunchCache = 0x1738； 双字 iIDentIndex = 0x153C； 双字 iTeamNum = 0x3BF; DWORD相机服务 = 0x10E0; 双字 iFovStart = 0x214； 双字 fFlags = 0x3C8； DWORD bSpottedByMask = 0x1630 + 0xC；//entitySpottedState + bSpottedByMask } Pawn;
> 
> 结构 { DWORD 当前健康状况 = 0x2A8; // m_iHealth } ServerPawn;
> 
> 结构体 { DWORD dwPlantedC4 = 0x189DAF8; 双字实时 = 0x00； 双字计数帧 = 0x04； DWORD 最大客户端数 = 0x10； 双字每次间隔 = 0x14； DWORD 当前时间 = 0x2C； 双字当前时间2 = 0x30； 双字滴答计数 = 0x40； DWORD IntervalPerTick2 = 0x44； 双字当前Netchan = 0x0048； DWORD 当前映射 = 0x0180； DWORD 当前地图名称 = 0x0188； 全局变量；
> 
> 结构体 { DWORD m_hPawn = 0x5F4; 双字节 m_pObserverServices = 0x10C0; 双字节 m_hObserverTarget = 0x44; DWORD m_hController = 0x123C； } 玩家控制器；
> 
> 结构体 { DWORD m_szName = 0xC18; 武器库数据；
> 
> 结构体 { DWORD m_bBeingDefused = 0xEBC; DWORD m_flDefuseCountDown = 0xED0; 双字节 m_nBombSite = 0xE84; C4； // 永远不要尝试外部换肤器 结构 { DWORD MusicID = 0x40; 双字等级 = 0x44； DWORD 权威武器槽 = 0x70; } 存货;
> 
> 命名空间签名 { const std::string InventoryServices = "E8 ?? ?? ?? ?? 8B 45 D0 48 8B 55 D8"; const std::string GlobalVars = "48 89 0D ?? ?? ?? ?? 48 89 41"; const std::string EntityList = "48 8B 0D ?? ?? ?? ?? 48 89 7C 24 ?? 8B FA C1"; const std::string LocalPlayerController = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 4F"; const std::string ViewAngles = "48 8B 0D ?? ?? ?? ?? 48 8B 01 48 FF 60 30"; const std::string ViewMatrix = "48 8D 0D ?? ?? ?? ?? 48 C1 E0 06"; const std::string LocalPlayerPawn = "48 8D 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 48 83 EC ?? 8B 0D"; const std::string ForceJump = "48 8B 05 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 89 45"; }

aimbot

**Comment by pipi-ly** [comment]
Offset::ViewAngle = TempAddress + 0x5328 - ClientDLL;

**Comment by pipi-ly** [comment]
> > 结构 { DWORD 健康 = 0x32C; 双字组 ID = 0x3BF; 双字节 IsAlive = 0x7DC; DWORD PlayerPawn = 0x7D4; DWORD iszPlayerName = 0x628; 双字敌人传感器 = 0x13DC; DWORD 重力重力桥梁 = 0x434;
> > 结构 { DWORD BulletServices = 0x16B0;DWORD 总命中 = 0x40; 双字位置 = 0x1224; 双字最大健康 = 0x328; DWORD 当前状况健康 = 0x32C; DWORD 游戏场景节点 = 0x310;DWORD BoneArray = 0x1E0; 双字 angEyeAngles = 0x1510;DWORD vecLastClipCameraPos = 0x128C; 双字 pClippingWeapon = 0x12A8; 双字 iShotsFired = 0x1418; 双字 flFlashDuration = 0x1468; DWORD targetPunchAngle = 0x1714; 双字型 TargetPunchCache = 0x1738; 双字 iIDentIndex = 0x153C; 双字 iTeamNum = 0x3BF;DWORD相机服务 = 0x10E0;双字 iFovStart = 0x214; 双字 fFlags = 0x3C8; DWORD bSpottedByMask = 0x1630 + 0xC;//entitySpottedState + bSpottedByMask } Pawn;
> > 结构 { DWORD 当前健康状况 = 0x2A8; // m_iHealth } ServerPawn;
> > 结构体 { DWORD dwPlantedC4 = 0x189DAF8; 双字实时 = 0x00; 双字计数帧 = 0x04; DWORD 最大客户端数 = 0x10; 双字每次间隔 = 0x14; DWORD 当前时间 = 0x2C; 双字当前时间2 = 0x30; 双字滴答计数 = 0x40; DWORD IntervalPerTick2 = 0x44; 双字当前Netchan = 0x0048; DWORD 当前映射 = 0x0180; DWORD 当前地图名称 = 0x0188; 全局变量;
> > 结构体 { DWORD m_hPawn = 0x5F4; 双字节 m_pObserverServices = 0x10C0; 双字节 m_hObserverTarget = 0x44;DWORD m_hController = 0x123C; } 玩家控制器;
> > 结构体 { DWORD m_szName = 0xC18; 武器库数据;
> > 结构体 { DWORD m_bBeingDefused = 0xEBC;DWORD m_flDefuseCountDown = 0xED0;双字节 m_nBombSite = 0xE84;C4; // 永远不要尝试外部换肤器 结构 { DWORD MusicID = 0x40; 双字等级 = 0x44; DWORD 权威武器槽 = 0x70; } 存货;
> > 命名空间签名 { const std：：string InventoryServices = “E8 ?? ?? ?? ??8B、45、D0、48、8B、55、D8“;const std：：string GlobalVars = “48 89 0D ?? ?? ?? ??48 89 41";const std：：string EntityList = “48 8B 0D ?? ?? ?? ??48 89 7C 24 ？？8B FA C1“;const std：：string LocalPlayerController = “48 8B 05 ?? ?? ?? ??48 85 C0 74 4F“;const std：：string ViewAngles = “48 8B 0D ?? ?? ?? ??48 8B 01 48 FF 60 30“;const std：：string ViewMatrix = “48 8D0D ？？??????48 C1 E0 06“;const std：：string LocalPlayerPawn = “48 8D05 ????????C3 CC CC CC CC 48 83 EC ？？8B 0D“;const std：：string ForceJump = “48 8B 05 ?? ?? ?? ??48 8D的1D ？？??????48 89 45";}
> 
> AIMBOT机器人
 in Offset.cpp
Offset::ViewAngle = TempAddress + 0x5328 - ClientDLL;

**Comment by dongyoxuan1514** [comment]
> > > 结构 { DWORD 健康 = 0x32C; 双字组 ID = 0x3BF; 双字节 IsAlive = 0x7DC; DWORD PlayerPawn = 0x7D4；DWORD iszPlayerName = 0x628; 双字敌人传感器 = 0x13DC; DWORD 重力重力桥梁 = 0x434;
> > > 结构 { DWORD BulletServices = 0x16B0;DWORD 总命中 = 0x40; 双字位置 = 0x1224; 双字最大健康 = 0x328; DWORD 当前状况健康 = 0x32C; DWORD 游戏节点 = 0x310;DWORD BoneArray = 0x1E0; 双字 angEyeAngles = 0x1510;DWORD vecLastClipCameraPos = 0x128C; 双字 pClippingWeapon = 0x12A8; 双字 iShotsFired = 0x1418; 双字 flFlashDuration = 0x1468; 双字目标PunchAngle = 0x1714；双字型 TargetPunchCache = 0x1738; 双字 iIDentIndex = 0x153C; 双字 iTeamNum = 0x3BF;DWORD 相机服务 = 0x10E0;双字 iFovStart = 0x214; 双字 fFlags = 0x3C8; DWORD bSpottedByMask = 0x1630 + 0xC;//entitySpottedState + bSpottedByMask } Pawn;
> > > 结构 { DWORD 当前健康状况 = 0x2A8; // m_iHealth } ServerPawn;
> > > 结构体 { DWORD dwPlantedC4 = 0x189DAF8; 双字实时 = 0x00; 双字计数帧 = 0x04; DWORD 最大客户端数 = 0x10; 双字每次间隔 = 0x14; DWORD 当前时间 = 0x2C; 双字当前时间2 = 0x30; 双字滴答计数 = 0x40; DWORD IntervalPerTick2 = 0x44；双字当前Netchan = 0x0048; DWORD 当前映射 = 0x0180；DWORD 当前地图名称 = 0x0188; 全局变量;
> > > 结构体 { DWORD m_hPawn = 0x5F4; 双字节 m_pObserverServices = 0x10C0; 双字节 m_hObserverTarget = 0x44;DWORD m_hController = 0x123C; } 玩家控制器;
> > > 结构体 { DWORD m_szName = 0xC18; 库武器数据;
> > > 结构体 { DWORD m_bBeingDefused = 0xEBC;DWORD m_flDefuseCountDown = 0xED0;双字节 m_nBombSite = 0xE84;C4; // 永远不要尝试外部换肤器结构 { DWORD MusicID = 0x40; 双字等级 = 0x44; DWORD 权威武器槽 = 0x70; } 存货;
> > > 命名空间签名 { const std：：string InventoryServices = “E8 ?? ?? ?? ??8B、45、D0、48、8B、55、D8“;const std：：string GlobalVars = “48 89 0D ?? ?? ?? ??48 89 41";const std：：string EntityList = “48 8B 0D ?? ?? ?? ??48 89 7C 24 ？？8B FA C1“;const std：：string LocalPlayerController = “48 8B 05 ?? ?? ?? ??48 85 C0 74 4F“;const std：：string ViewAngles = “48 8B 0D ?? ?? ?? ??48 8B 01 48 FF 60 30“;const std：：string ViewMatrix = “48 8D0D ？？？？？？？48 C1 E0 06“;const std：：string LocalPlayerPawn = “48 8D05 ?????????C3 CC CC CC CC 48 83 EC ？？8B 0D“;const std： ：string ForceJump = “48 8B 05 ?? ?? ?? ??48 8D的1D ？？？？？？？48 89 45";}
> > 
> > 
> > AIMBOT机器人
> > 中Offset.cpp 
> > Offset::ViewAngle = TempAddress + 0x5328 - ClientDLL;

thank bro ！！！

**Comment by syafiq99121** [comment]
> struct { DWORD Health = 0x32C; DWORD TeamID = 0x3BF; DWORD IsAlive = 0x7DC; DWORD PlayerPawn = 0x7D4; DWORD iszPlayerName = 0x628; DWORD EnemySensor = 0x13DC; DWORD GravityScale = 0x434; } Entity;
> 
> struct { DWORD BulletServices = 0x16B0; DWORD TotalHit = 0x40; DWORD Pos = 0x1224; DWORD MaxHealth = 0x328; DWORD CurrentHealth = 0x32C; DWORD GameSceneNode = 0x310; DWORD BoneArray = 0x1E0; DWORD angEyeAngles = 0x1510; DWORD vecLastClipCameraPos = 0x128C; DWORD pClippingWeapon = 0x12A8; DWORD iShotsFired = 0x1418; DWORD flFlashDuration = 0x1468; DWORD aimPunchAngle = 0x1714; DWORD aimPunchCache = 0x1738; DWORD iIDEntIndex = 0x153C; DWORD iTeamNum = 0x3BF; DWORD CameraServices = 0x10E0; DWORD iFovStart = 0x214; DWORD fFlags = 0x3C8; DWORD bSpottedByMask = 0x1630 + 0xC; // entitySpottedState + bSpottedByMask } Pawn;
> 
> struct { DWORD CurrentHealth = 0x2A8; // m_iHealth } ServerPawn;
> 
> struct { DWORD dwPlantedC4 = 0x189DAF8; DWORD RealTime = 0x00; DWORD FrameCount = 0x04; DWORD MaxClients = 0x10; DWORD IntervalPerTick = 0x14; DWORD CurrentTime = 0x2C; DWORD CurrentTime2 = 0x30; DWORD TickCount = 0x40; DWORD IntervalPerTick2 = 0x44; DWORD CurrentNetchan = 0x0048; DWORD CurrentMap = 0x0180; DWORD CurrentMapName = 0x0188; } GlobalVar;
> 
> struct { DWORD m_hPawn = 0x5F4; DWORD m_pObserverServices = 0x10C0; DWORD m_hObserverTarget = 0x44; DWORD m_hController = 0x123C; } PlayerController;
> 
> struct { DWORD m_szName = 0xC18; } WeaponBaseData;
> 
> struct { DWORD m_bBeingDefused = 0xEBC; DWORD m_flDefuseCountDown = 0xED0; DWORD m_nBombSite = 0xE84; } C4; // Never have a try for external skin changer struct { DWORD MusicID = 0x40; DWORD Rank = 0x44; DWORD AuthoritativeWeaponSlots = 0x70; } Inventory;
> 
> namespace Signatures { const std::string InventoryServices = "E8 ?? ?? ?? ?? 8B 45 D0 48 8B 55 D8"; const std::string GlobalVars = "48 89 0D ?? ?? ?? ?? 48 89 41"; const std::string EntityList = "48 8B 0D ?? ?? ?? ?? 48 89 7C 24 ?? 8B FA C1"; const std::string LocalPlayerController = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 4F"; const std::string ViewAngles = "48 8B 0D ?? ?? ?? ?? 48 8B 01 48 FF 60 30"; const std::string ViewMatrix = "48 8D 0D ?? ?? ?? ?? 48 C1 E0 06"; const std::string LocalPlayerPawn = "48 8D 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 48 83 EC ?? 8B 0D"; const std::string ForceJump = "48 8B 05 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 89 45"; }

where do I put this code, whether in offsets.cpp or in oiffsets.h??? some one help me

**Comment by dongyoxuan1514** [comment]
> > struct { DWORD Health = 0x32C; DWORD TeamID = 0x3BF; DWORD IsAlive = 0x7DC; DWORD PlayerPawn = 0x7D4; DWORD iszPlayerName = 0x628; DWORD EnemySensor = 0x13DC; DWORD GravityScale = 0x434; } Entity;
> > struct { DWORD BulletServices = 0x16B0; DWORD TotalHit = 0x40; DWORD Pos = 0x1224; DWORD MaxHealth = 0x328; DWORD CurrentHealth = 0x32C; DWORD GameSceneNode = 0x310; DWORD BoneArray = 0x1E0; DWORD angEyeAngles = 0x1510; DWORD vecLastClipCameraPos = 0x128C; DWORD pClippingWeapon = 0x12A8; DWORD iShotsFired = 0x1418; DWORD flFlashDuration = 0x1468; DWORD aimPunchAngle = 0x1714; DWORD aimPunchCache = 0x1738; DWORD iIDEntIndex = 0x153C; DWORD iTeamNum = 0x3BF; DWORD CameraServices = 0x10E0; DWORD iFovStart = 0x214; DWORD fFlags = 0x3C8; DWORD bSpottedByMask = 0x1630 + 0xC; // entitySpottedState + bSpottedByMask } Pawn;
> > struct { DWORD CurrentHealth = 0x2A8; // m_iHealth } ServerPawn;
> > struct { DWORD dwPlantedC4 = 0x189DAF8; DWORD RealTime = 0x00; DWORD FrameCount = 0x04; DWORD MaxClients = 0x10; DWORD IntervalPerTick = 0x14; DWORD CurrentTime = 0x2C; DWORD CurrentTime2 = 0x30; DWORD TickCount = 0x40; DWORD IntervalPerTick2 = 0x44; DWORD CurrentNetchan = 0x0048; DWORD CurrentMap = 0x0180; DWORD CurrentMapName = 0x0188; } GlobalVar;
> > struct { DWORD m_hPawn = 0x5F4; DWORD m_pObserverServices = 0x10C0; DWORD m_hObserverTarget = 0x44; DWORD m_hController = 0x123C; } PlayerController;
> > struct { DWORD m_szName = 0xC18; } WeaponBaseData;
> > struct { DWORD m_bBeingDefused = 0xEBC; DWORD m_flDefuseCountDown = 0xED0; DWORD m_nBombSite = 0xE84; } C4; // Never have a try for external skin changer struct { DWORD MusicID = 0x40; DWORD Rank = 0x44; DWORD AuthoritativeWeaponSlots = 0x70; } Inventory;
> > namespace Signatures { const std::string InventoryServices = "E8 ?? ?? ?? ?? 8B 45 D0 48 8B 55 D8"; const std::string GlobalVars = "48 89 0D ?? ?? ?? ?? 48 89 41"; const std::string EntityList = "48 8B 0D ?? ?? ?? ?? 48 89 7C 24 ?? 8B FA C1"; const std::string LocalPlayerController = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 4F"; const std::string ViewAngles = "48 8B 0D ?? ?? ?? ?? 48 8B 01 48 FF 60 30"; const std::string ViewMatrix = "48 8D 0D ?? ?? ?? ?? 48 C1 E0 06"; const std::string LocalPlayerPawn = "48 8D 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 48 83 EC ?? 8B 0D"; const std::string ForceJump = "48 8B 05 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 89 45"; }
> 
> where do I put this code, whether in offsets.cpp or in oiffsets.h??? some one help me

offset.h

**Comment by TKazer** [comment]
No further updates will be provided here。
