### ISSUE TITLE
CS2 Updated again (2023-11-16) OffSets?

### ISSUE THREAD

**Issue by toxic-grl** [TKazer/CS2_External#140]
Does anyone have the new offsets?

Thanks

**Comment by pipi-ly** [comment]
I fixed the OffSets, but the box is not on the enemy

**Comment by dongyoxuan1514** [comment]
> 我修复了偏移，但盒子不在敌人身上

I'd like to ask if you have any contact information? I would like to ask you about offset issues wechat or qq

**Comment by pipi-ly** [comment]
wechat ：LY2575922186

**Comment by dongyoxuan1514** [comment]
> I fixed the OffSets, but the box is not on the enemy



> I fixed the OffSets, but the box is not on the enemy

Bro, can you update the offset?
