### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by KGAT1W** [TKazer/CS2_External#152]
struct
	{
		DWORD Health = 0x7F8; // m_iPawnHealth 
		DWORD TeamID = 0x3BF; // m_iTeamNum 
		DWORD IsAlive = 0x7F4; // m_bPawnIsAlive 
		DWORD PlayerPawn = 0x7EC; // m_hPlayerPawn 
		DWORD iszPlayerName = 0x640; // m_iszPlayerName 
	}Entity;

	struct
	{
		DWORD BulletServices = 0x16B8; // m_pBulletServices 
		DWORD TotalHit = 0x40; // m_totalHitsOnServer 
		DWORD Pos = 0x1224; // m_vOldOrigin 
		DWORD MaxHealth = 0x328; // m_iMaxHealth 
		DWORD CurrentHealth = 0x32C; // m_iHealth 
		DWORD GameSceneNode = 0x310; // m_pGameSceneNode 
		DWORD BoneArray = 0x1E0; // m_nBoneIndex  ?? что то другое
		DWORD angEyeAngles = 0x1518; // m_angEyeAngles 
		DWORD vecLastClipCameraPos = 0x1294; // m_vecLastClipCameraPos 
		DWORD pClippingWeapon = 0x12B0; // m_pClippingWeapon 
		DWORD iShotsFired = 0x1420; // m_iShotsFired 
		DWORD flFlashDuration = 0x1470; // m_flFlashDuration 
		DWORD aimPunchAngle = 0x171C; // m_aimPunchAngle 
		DWORD aimPunchCache = 0x1740; // m_aimPunchCache 
		DWORD iIDEntIndex = 0x1544; // m_iIDEntIndex 
		DWORD iTeamNum = 0x3BF; // m_iTeamNum 
		DWORD CameraServices = 0x10E0; // m_pCameraServices 
		DWORD iFovStart = 0x214; // m_iFOVStart 
		DWORD fFlags = 0x3C8; // m_fFlags 
		DWORD bSpottedByMask = 0x1A48 + 0xC; // entitySpottedState + bSpottedByMask
	}Pawn;

	struct
	{
		DWORD m_bBeingDefused = 0xEBC; // m_bBeingDefused 
		DWORD m_flDefuseCountDown = 0xED0; // m_flDefuseCountDown 
		DWORD m_nBombSite = 0xE84; // m_nBombSite 
	} C4;

	struct
	{
		DWORD RealTime = 0x00;
		DWORD FrameCount = 0x04;
		DWORD MaxClients = 0x10;
		DWORD IntervalPerTick = 0x14;
		DWORD CurrentTime = 0x2C;
		DWORD CurrentTime2 = 0x30;
		DWORD TickCount = 0x40;
		DWORD IntervalPerTick2 = 0x44;
		DWORD CurrentNetchan = 0x0048;
		DWORD CurrentMap = 0x0180;
		DWORD CurrentMapName = 0x0188;
	} GlobalVar;

**Comment by toxic-grl** [comment]
It works for the most part, but there are weapons that when others use them or you buy them you don't see the wallhack
tec9 - cz75 - ssg08 - smg - sg553 and xm1014

we have to change this line in offsets.cpp

Offset::View Angle = TempAddress + 24896 - ClientDLL;

but I don't know which is the correct new one

**Comment by KGAT1W** [comment]
ViewAngle still 24896

**Comment by Sahashirokov** [comment]
pls update offsets

**Comment by JLWLL** [comment]
> ```
> struct
> {
> 	DWORD Health = 0x7F8; // m_iPawnHealth 
> 	DWORD TeamID = 0x3BF; // m_iTeamNum 
> 	DWORD IsAlive = 0x7F4; // m_bPawnIsAlive 
> 	DWORD PlayerPawn = 0x7EC; // m_hPlayerPawn 
> 	DWORD iszPlayerName = 0x640; // m_iszPlayerName 
> }Entity;
> 
> struct
> {
> 	DWORD BulletServices = 0x16B8; // m_pBulletServices 
> 	DWORD TotalHit = 0x40; // m_totalHitsOnServer 
> 	DWORD Pos = 0x1224; // m_vOldOrigin 
> 	DWORD MaxHealth = 0x328; // m_iMaxHealth 
> 	DWORD CurrentHealth = 0x32C; // m_iHealth 
> 	DWORD GameSceneNode = 0x310; // m_pGameSceneNode 
> 	DWORD BoneArray = 0x1E0; // m_nBoneIndex  ?? что то другое
> 	DWORD angEyeAngles = 0x1518; // m_angEyeAngles 
> 	DWORD vecLastClipCameraPos = 0x1294; // m_vecLastClipCameraPos 
> 	DWORD pClippingWeapon = 0x12B0; // m_pClippingWeapon 
> 	DWORD iShotsFired = 0x1420; // m_iShotsFired 
> 	DWORD flFlashDuration = 0x1470; // m_flFlashDuration 
> 	DWORD aimPunchAngle = 0x171C; // m_aimPunchAngle 
> 	DWORD aimPunchCache = 0x1740; // m_aimPunchCache 
> 	DWORD iIDEntIndex = 0x1544; // m_iIDEntIndex 
> 	DWORD iTeamNum = 0x3BF; // m_iTeamNum 
> 	DWORD CameraServices = 0x10E0; // m_pCameraServices 
> 	DWORD iFovStart = 0x214; // m_iFOVStart 
> 	DWORD fFlags = 0x3C8; // m_fFlags 
> 	DWORD bSpottedByMask = 0x1A48 + 0xC; // entitySpottedState + bSpottedByMask
> }Pawn;
> 
> struct
> {
> 	DWORD m_bBeingDefused = 0xEBC; // m_bBeingDefused 
> 	DWORD m_flDefuseCountDown = 0xED0; // m_flDefuseCountDown 
> 	DWORD m_nBombSite = 0xE84; // m_nBombSite 
> } C4;
> 
> struct
> {
> 	DWORD RealTime = 0x00;
> 	DWORD FrameCount = 0x04;
> 	DWORD MaxClients = 0x10;
> 	DWORD IntervalPerTick = 0x14;
> 	DWORD CurrentTime = 0x2C;
> 	DWORD CurrentTime2 = 0x30;
> 	DWORD TickCount = 0x40;
> 	DWORD IntervalPerTick2 = 0x44;
> 	DWORD CurrentNetchan = 0x0048;
> 	DWORD CurrentMap = 0x0180;
> 	DWORD CurrentMapName = 0x0188;
> } GlobalVar;
> ```

So what is BoneArray ?

**Comment by floppa1511** [comment]
`DWORD bSpottedByMask = 0x1638 + 0xC;` fixed, use this or else aimbot wont work properly

**Comment by TKazer** [comment]
The offsets will not be updated.
