### ISSUE TITLE
Worki only on dust?

### ISSUE THREAD

**Issue by kura6789** [TKazer/CS2_External#3]
Thanks for share but its working on dust2 only. How to fix it? After cs2 update, offset updater stopped working too

**Comment by TKazer** [comment]
offset updater fixed. the first question will be solve soon.

**Comment by TKazer** [comment]
Fixed, it can adapt to all map now.

**Comment by kura6789** [comment]
Thanks! It is working now but in previous version we can turn off team ESP easier :D I added this to cheats.cpp
 ``PlayerController Controller;``
 
`` if (Controller.TeamID == Controller.TeamID)
	continue; ``
and this to Entity.cpp in bool CEntity::UpdatePawn(const DWORD64& PlayerPawnAddress)
`` if (!this->Controller.GetTeamID())
	return false; ``
	
But now it is not working. Im newbie here. Can u help?

**Comment by kura6789** [comment]
NVM fixed. I feel like profesional paster :D.
Solution:
just change this: `` if (Entity.TeamID == LocalEntity.TeamID)
	continue; ``
to this ``if (Entity.Controller.TeamID == LocalEntity.Controller.TeamID)`` in cheats.cpp

**Comment by TKazer** [comment]
Yes ,I forgot to change this code after updating.
