### ISSUE TITLE
no ESP when spectate teammate.

### ISSUE THREAD

**Issue by exscreamo** [TKazer/CS2_External#42]
how to enable ESP when spectating a teammate?

**Comment by exscreamo** [comment]
no one can help?

**Comment by exscreamo** [comment]
@TKazer what to change if i want to see enemy ESP even when im spectating my teammate?

**Comment by Sigma12456** [comment]
you own health check

**Comment by exscreamo** [comment]
> you own health check

what do u mean?

**Comment by Fr0go1** [comment]
> > you own health check
> 
> what do u mean?

the cheat will check if your alive and if you are then i will continue, if you arnt then it will stop until you are

**Comment by exscreamo** [comment]
> > > you own health check
> > 
> > what do u mean?
> 
> the cheat will check if your alive and if you are then i will continue, if you arnt then it will stop until you are

ok thanks but which file do i need to change? or can u help to make one

**Comment by TookieBW** [comment]
debugged this and found a ghetto solution 
`if (!LocalEntity.UpdatePawn(LocalPawnAddress)) {
		//std::cout << "Test4" << std::endl;
		if (LocalEntity.IsAlive()) {
			return;
		}
	}`

**Comment by Henkdenk** [comment]
> debugged this and found a ghetto solution `if (!LocalEntity.UpdatePawn(LocalPawnAddress)) { //std::cout << "Test4" << std::endl; if (LocalEntity.IsAlive()) { return; } }`

where to paste this ? :nerd:

**Comment by Fr0go1** [comment]
> > debugged this and found a ghetto solution `if (!LocalEntity.UpdatePawn(LocalPawnAddress)) { //std::cout << "Test4" << std::endl; if (LocalEntity.IsAlive()) { return; } }`
> 
> where to paste this ? :nerd:

you can do something like this https://github.com/Fr0go1/Aeonix-Cs2/blob/72328941298a464f56acbc5473a2bb74f0f86a41/CS2_External/Cheats.cpp#L280
