### ISSUE TITLE
Radar like Aimware

### ISSUE THREAD

**Issue by CowNowK** [TKazer/CS2_External#46]
雷达窗口可以默认附着在屏幕左上角；然后设置窗口独立样式，背景颜色透明度高一点；Proportion设置到2580。就可以得到一个和Aimware几乎一样的雷达
![pic](https://github.com/TKazer/CS2_External/assets/133740174/321ee9c6-472c-44ba-beef-a5e05dadefc9)
`Penis ESP was added by myself XD`

**Comment by TKazer** [comment]
这个可以自行调整，我在这就不做添加了

**Comment by Henkdenk** [comment]
Sexy ESP

**Comment by CowNowK** [comment]
> Sexy ESP

My project has been released, and you can find my derivative projects in the `README` or `fork`.

**Comment by dasstf** [comment]
> > Sexy ESP
> 
> My project has been released, and you can find my derivative projects in the `README` or `fork`.
![image](https://github.com/TKazer/CS2_External/assets/94780138/6a9d0d9f-f753-4bba-b908-621453a84dc2)

your project report a error，how to solve it

**Comment by dasstf** [comment]
> > Sexy ESP
> 
> My project has been released, and you can find my derivative projects in the `README` or `fork`.

thanks a lot plz
