### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by mandlw** [TKazer/CS2_External#49]
ive ran into countless errors such as msbuild not even having the right path and im just about to give up with building and compiling this ive just ran into another error and i am requesting help on how to build, compile and debug 
![image_2023-10-04_181157258](https://github.com/TKazer/CS2_External/assets/147009391/e93251ec-49ad-43b1-abb3-d2d328a49e83)

**Comment by mildnsj** [comment]
Just use visual studio, open sln, compile, thats it.

**Comment by mandlw** [comment]
it just gives me error msb1003 when i try to do that

**Comment by mandlw** [comment]
how it just says this 
![image_2023-10-04_214152793](https://github.com/TKazer/CS2_External/assets/147009391/56b4709d-ddba-47ca-86ec-df8e2bb8c6bf)

**Comment by mandlw** [comment]
is there any way to reinstall msbuild without breaking things bacsue i have the 2012 version and its in C:\Windows\Microsoft.NET\Framework64\v4.0.30319 instead of C:\Program Files (x86)\MSBuild\14.0\Bin or a visual studio folder

**Comment by mandlw** [comment]
nvm i fixed it
