### ISSUE TITLE
cant compile cuz i have errors

### ISSUE THREAD

**Issue by d3mxx** [TKazer/CS2_External#51]
idk what i should do
![image](https://github.com/TKazer/CS2_External/assets/131014190/1a2676f7-4c1d-4444-bc37-e983787b12f9)
![image](https://github.com/TKazer/CS2_External/assets/131014190/cb145d9c-a819-44c9-b6c2-22b66afecd88)

**Comment by CowNowK** [comment]
If you just want to use the cheat and don't care about the code, you can find my project `Aimstar` in the **README** or **Fork**. I compiled and released🥴But remember use at your own risk

**Comment by Henkdenk** [comment]
works like a charm

**Comment by CowNowK** [comment]
> idk what i should do ![image](https://user-images.githubusercontent.com/131014190/272987402-1a2676f7-4c1d-4444-bc37-e983787b12f9.png) ![image](https://user-images.githubusercontent.com/131014190/272987465-cb145d9c-a819-44c9-b6c2-22b66afecd88.png)

Did you install the Win10 SDK when installing Visual Studio?

**Comment by exscreamo** [comment]
@CowNowK im using ur aimstar project. it works. the only problem is when u die and spectate teammate, enemy ESP are not visible.

**Comment by CowNowK** [comment]
> @CowNowK im using ur aimstar project. it works. the only problem is when u die and spectate teammate, enemy ESP are not visible.

@exscreamo The original project is designed this way, so it is not considered a bug.

**Comment by exscreamo** [comment]
@CowNowK do u know what to change if i want ESP still visible when spectating teammate?

**Comment by CowNowK** [comment]
> @CowNowK do u know what to change if i want ESP still visible when spectating teammate?

@exscreamo In the ESP rendering loop, the "continue" statement is used to skip iterations when a specific condition is not met. So you can try removing certain conditional code to see which part is skipping the spectators.
I have no intention of fixing this issue, so I haven't tried it yet. However, you can give it a try and see

**Comment by d3mxx** [comment]
> If you just want to use the cheat and don't care about the code, you can find my project `Aimstar` in the **README** or **Fork**. I compiled and released🥴But remember use at your own risk

thanks, bro it's works i'm just dumbass and forgot abt win10 sdk
