### ISSUE TITLE
Why is there no response after pressing any key

### ISSUE THREAD

**Issue by moxtj** [TKazer/CS2_External#56]
![image](https://github.com/TKazer/CS2_External/assets/146818710/a58c3f2b-3634-4f09-8363-fe7ce3c1027f)[
![image](https://github.com/TKazer/CS2_External/assets/146818710/06b47ddc-39f5-459c-af6e-517067bd2951)
](url)

**Comment by TKazer** [comment]
你是用于国内平台，请自行更改启动代码来适配窗口名，另外本源码并没有针对反作弊做处理。
