### ISSUE TITLE
Config folder change

### ISSUE THREAD

**Issue by kirill-21** [TKazer/CS2_External#60]
It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.

**Comment by Sigma12456** [comment]
do it yourself.

**Comment by kirill-21** [comment]
> do it yourself.

You are not even the person who maintains this repo or contributes to it, do not answer people on behalf of the developer until this mod belongs to you

**Comment by Fr0go1** [comment]
> It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.

so you want it to save to like in a folder in the windows temp folder or something?

**Comment by kirill-21** [comment]
> > It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.
> 
> so you want it to save to like in a folder in the windows temp folder or something?

I think modification should use some path that will be identical on all computers, for example appdata or documents

**Comment by Fr0go1** [comment]
> > > It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.
> > 
> > 
> > so you want it to save to like in a folder in the windows temp folder or something?
> 
> I think modification should use some path that will be identical on all computers, for example appdata or documents

ok i could add it and either make a pull req or just give you the code, (after school though)

**Comment by kirill-21** [comment]
> > > > It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.
> > > 
> > > 
> > > so you want it to save to like in a folder in the windows temp folder or something?
> > 
> > 
> > I think modification should use some path that will be identical on all computers, for example appdata or documents
> 
> ok i could add it and either make a pull req or just give you the code, (after school though)

Pull request sounds better since I'm not the only one with such error

**Comment by Fr0go1** [comment]
> > > > > It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.
> > > > 
> > > > 
> > > > so you want it to save to like in a folder in the windows temp folder or something?
> > > 
> > > 
> > > I think modification should use some path that will be identical on all computers, for example appdata or documents
> > 
> > 
> > ok i could add it and either make a pull req or just give you the code, (after school though)
> 
> Pull request sounds better since I'm not the only one with such error

git hub is being a bitch and not letting me upload to forks so i cant make a pull request so i just made my own repo

https://github.com/Fr0go1/Aeonix-Cs2

**Comment by kirill-21** [comment]
> > > > > > It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.
> > > > > 
> > > > > 
> > > > > so you want it to save to like in a folder in the windows temp folder or something?
> > > > 
> > > > 
> > > > I think modification should use some path that will be identical on all computers, for example appdata or documents
> > > 
> > > 
> > > ok i could add it and either make a pull req or just give you the code, (after school though)
> > 
> > 
> > Pull request sounds better since I'm not the only one with such error
> 
> git hub is being a bitch and not letting me upload to forks so i cant make a pull request so i just made my own repo
> 
> https://github.com/Fr0go1/Aeonix-Cs2
> 
> it has the config shit in it

You can not make a pull request since you've uploaded files without forking.

1. Download your repo files
2. Delete your repo
3. Go to https://github.com/TKazer/CS2_External and press Fork at the right-corner part
4. Go to your forked repo, git clone in on the disk, replace files with those you've cached in step 1
5. Make a git push to your own repo
6. Now you can create a pull request

Using a version from somebody else' repo is bad because it's not updated when this repo is updated

**Comment by kirill-21** [comment]
> > > > > > > > It would be great in configs folder is changed to some static one, for example Documents/Tkazer, since on some windows versions cfg might be placed not to the folder where mod's executable is located, but to the working directory of the cmd, which will be C:\Windows\System32 (especially related to UNC error), that might lead to access_denied error since creation of files in that folder works bad on some systems.
> > > > > > > 
> > > > > > > 
> > > > > > > so you want it to save to like in a folder in the windows temp folder or something?
> > > > > > 
> > > > > > 
> > > > > > I think modification should use some path that will be identical on all computers, for example appdata or documents
> > > > > 
> > > > > 
> > > > > ok i could add it and either make a pull req or just give you the code, (after school though)
> > > > 
> > > > 
> > > > Pull request sounds better since I'm not the only one with such error
> > > 
> > > 
> > > git hub is being a bitch and not letting me upload to forks so i cant make a pull request so i just made my own repo
> > > https://github.com/Fr0go1/Aeonix-Cs2
> > > it has the config shit in it
> > 
> > 
> > You can not make a pull request since you've uploaded files without forking.
> > 
> > 1. Download your repo files
> > 2. Delete your repo
> > 3. Go to https://github.com/TKazer/CS2_External and press Fork at the right-corner part
> > 4. Go to your forked repo, git clone in on the disk, replace files with those you've cached in step 1
> > 5. Make a git push to your own repo
> > 6. Now you can create a pull request
> > 
> > Using a version from somebody else' repo is bad because it's not updated when this repo is updated
> 
> i mean i cant upload properly from visual studio to a forked repos

You can use a cmd to do it

**Comment by kirill-21** [comment]
![image](https://github.com/TKazer/CS2_External/assets/63228361/ef910e6a-c3c0-46ba-b453-2054d44ea26e)

Press this button, open cmd in any folder any type
```
git clone https://github.com/Fr0go1/CS2_External
```

change files to your backup copy

open cmd one more time(in the same folder)

type
```
git add .
```
```
git commit -m "changed configs folder"
```
```
git push origin master
```
