### ISSUE TITLE
关于一处代码的堆内存处理

### ISSUE THREAD

**Issue by INKCR0W** [TKazer/CS2_External#65]
**事先叠甲我是个小白**

在阅读代码时，我发现有一处[代码](https://github.com/TKazer/CS2_External/blob/master/CS2_External/Utils/MemorySearch.cpp#L100)似乎在释放内存之前就直接return了

似乎 大概 也许 有可能 会造成内存泄漏

**Comment by TKazer** [comment]
确实，这里会造成内存泄露，我会尽快修复，谢谢提醒。

**Comment by TKazer** [comment]
Fixed.
