### ISSUE TITLE
about 84 mistakes

### ISSUE THREAD

**Issue by KGB121** [TKazer/CS2_External#78]
![image](https://github.com/TKazer/CS2_External/assets/147476709/cef4c847-0f53-4e19-b16c-39cecda2399f)
i did nothing since i download it and i used the vs2022

**Comment by Sigma12456** [comment]
use dark mode: fixes 83 mistakes. the last mistake is your life. take you life

**Comment by TKazer** [comment]
fixed, the "render.hpp" file has different encoding.
