### ISSUE TITLE
[OS-Exception] DestWindow isn't exist

### ISSUE THREAD

**Issue by zzz9h** [TKazer/CS2_External#79]
![image](https://github.com/TKazer/CS2_External/assets/45917646/8e0a4a29-5a10-43c1-9bb4-8f7aae70ae2e)

**Comment by TKazer** [comment]
you need to modify the window name when call Gui.AttachAnotherWindow();

**Comment by woai1023** [comment]
wdf
how to do this

**Comment by woai1023** [comment]
i need help
