### ISSUE TITLE
Some missing features and enhancement:

### ISSUE THREAD

**Issue by deathruned** [TKazer/CS2_External#80]
- [ ] Triggerbot hitchance
- [ ] C4 Carrier
- [ ] Better font + Center weapon names on bottom esp
- [ ] Where the C4 is planted + How long it takes to get defuse or get exploded + C4 damage radius on player.
- [ ] Nade Trajectory and warning or show what projectiles are thrown
- [ ] Glow ESP (Health based)
- [ ] Crosshair for snipers only
- [ ] fast stop or auto stop / Auto duck when shooting.
- [ ] Fixing aimpos on aimbot because it only aim at head it doesn't matter where you aim.

**Comment by Fr0go1** [comment]
if you change the triggerbot delay it can work like hit chance

**Comment by bruhmoment-99** [comment]
glow esp is detected?

**Comment by Sigma12456** [comment]
kys

**Comment by deathruned** [comment]
> if you change the triggerbot delay it can work like hit chance

nope it doesn't work as it looks.

**Comment by JannesBonk** [comment]
> * [ ]  Triggerbot hitchance
Maybe possible but SDK is limited
> * [ ]  C4 Carrier
Possible
> * [ ]  Better font + Center weapon names on bottom esp
Possible 100%
> * [ ]  Where the C4 is planted + How long it takes to get defuse or get exploded + C4 damage radius on player.
Possible - Probably possible - Maybe possible but once again SDK limitations
> * [ ]  Nade Trajectory and warning or show what projectiles are thrown
Probably possible
> * [ ]  Glow ESP (Health based)
Instant detection
> * [ ]  Crosshair for snipers only
Possible but SDK limitations
> * [ ]  fast stop or auto stop / Auto duck when shooting.
Possible but also detected
> * [ ]  Fixing aimpos on aimbot because it only aim at head it doesn't matter where you aim.
Possible
