### ISSUE TITLE
Add custom font to the menu and customizable styles

### ISSUE THREAD

**Issue by Thugilmo** [TKazer/CS2_External#92]
Menu would look a lot better by just adding a font, instead of using default ImGui one.
Also the hability to swich themes or even customize  menu colors.

**Comment by Marcis2** [comment]
Just change your menu font yourself
https://github.com/ocornut/imgui/blob/master/docs/FONTS.md

**Comment by Thugilmo** [comment]
Honestly, I tried, but cheat keeps crashing, I have no idea what im doing wrong here :(

**Comment by Fr0go1** [comment]
> Menu would look a lot better by just adding a font, instead of using default ImGui one. Also the hability to swich themes or even customize menu colors.

my version has a changed front just copy what i did

**Comment by TKazer** [comment]
Please modify the menu style yourself, this project is only for learning reference.
